version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "9212:9211"
    depends_on:
      - mysql_db
    command: sh -c './wait-for mysql_db:3306 -- npm start'
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - app_test_db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: app_test_db
      MYSQL_USER: user_giash
      MYSQL_PASSWORD: nE5kMc7JCGNqwDQM
      MYSQL_ROOT_PASSWORD: nE5kMc7JCGNqwDQN
volumes:
  app_test_db_data:
